import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "../components/ui/ThemeToggle";
import {
  Cog6ToothIcon,
  PencilSquareIcon,
  EyeIcon,
  ArrowRightStartOnRectangleIcon,
  Bars3Icon,
} from "@heroicons/react/20/solid";
import Logo from "../components/ui/Logo";
import Link from "next/link";
import { auth, signOut } from "@/../auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  async function signOutAction() {
    "use server";
    await signOut();
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background text-foreground`}
      >
        <header className="bg-background border-b border-border">
          <div className="container-responsive flex items-center justify-between py-4 px-4 sm:px-6">
            <Link
              href="/"
              aria-label="Ir a inicio"
              className="flex items-center gap-2"
            >
              <Logo className="h-8 w-8" />
              <span className="text-sm md:text-base text-foreground font-semibold tracking-wide">
                CERTEZA
              </span>
            </Link>
            <nav className="flex items-center gap-2">
              <ThemeToggle />
              {session ? (
                <>
                  <div className="hidden sm:flex items-center gap-2">
                    <Link href="/admin" className="btn-secondary gap-2">
                      <Cog6ToothIcon
                        className="h-4 w-4 text-foreground"
                        aria-hidden="true"
                      />
                      Admin
                    </Link>
                    <Link href="/editor" className="btn-secondary gap-2">
                      <PencilSquareIcon
                        className="h-4 w-4 text-foreground"
                        aria-hidden="true"
                      />
                      Editor
                    </Link>
                    <Link href="/viewer" className="btn-secondary gap-2">
                      <EyeIcon
                        className="h-4 w-4 text-foreground"
                        aria-hidden="true"
                      />
                      Viewer
                    </Link>
                    <form action={signOutAction}>
                      <button className="btn-secondary gap-2">
                        <ArrowRightStartOnRectangleIcon
                          className="h-4 w-4 text-foreground"
                          aria-hidden="true"
                        />
                        Salir
                      </button>
                    </form>
                  </div>
                  <details className="relative sm:hidden">
                    <summary className="btn-secondary list-none flex items-center gap-2">
                      <Bars3Icon
                        className="h-4 w-4 text-foreground"
                        aria-hidden="true"
                      />
                      Menú
                    </summary>
                    <div className="absolute right-0 mt-2 w-40 rounded-lg border border-border bg-background shadow-md">
                      <div className="flex flex-col p-2">
                        <Link
                          href="/admin"
                          className="btn-secondary w-full gap-2"
                        >
                          <Cog6ToothIcon
                            className="h-4 w-4 text-foreground"
                            aria-hidden="true"
                          />
                          Admin
                        </Link>
                        <Link
                          href="/editor"
                          className="btn-secondary w-full mt-2 gap-2"
                        >
                          <PencilSquareIcon
                            className="h-4 w-4 text-foreground"
                            aria-hidden="true"
                          />
                          Editor
                        </Link>
                        <Link
                          href="/viewer"
                          className="btn-secondary w-full mt-2 gap-2"
                        >
                          <EyeIcon
                            className="h-4 w-4 text-foreground"
                            aria-hidden="true"
                          />
                          Viewer
                        </Link>
                        <form action={signOutAction} className="mt-2">
                          <button className="btn-secondary w-full gap-2">
                            <ArrowRightStartOnRectangleIcon
                              className="h-4 w-4 text-foreground"
                              aria-hidden="true"
                            />
                            Salir
                          </button>
                        </form>
                      </div>
                    </div>
                  </details>
                </>
              ) : null}
            </nav>
          </div>
        </header>
        <main className="w-full px-4 sm:px-6">{children}</main>
      </body>
    </html>
  );
}
